config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'posts#index'

  resources :posts do
    collection do
       get :draft
       get :subscribe
     end

     member do
       post 'like'
     end

     resources :comments, only: [:create, :edit, :update, :destroy]
   end

  devise_for :users
  resources :users, only: [:index]

  resources :comments, only: [:show] do
    member do
      post 'like'
      get 'replies'
    end

    resources :replies do
      member do
        post 'like'
      end
    end
  end

end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :comment
  has_many :likes, :as => :likeable

  validates :body, presence: true  
  #after_create was only working part of time here for some reason...so changed to using after_commit with create option
  after_commit :send_notification, on: [:create]

  def send_notification
    comment = self.comment
    user = self.user.email.split('@')[0]
    reply = self
    post = comment.post

    if comment.user.subscription? && comment.user != reply.user
      recipient = comment.user.email
      UserMailer.reply_notification(recipient, user, reply, post).deliver_later
    end
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  invisible_captcha only: [:create, :update], honeypot: :subtitle, on_spam: :spam_detected
  before_action :authorize_user
  before_action :set_comment, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :set_reply, only: [:edit, :update, :destroy, :like]

  def show
  end

  def new
    @reply = @comment.replies.new
  end

  def create
    @reply = @comment.replies.new(reply_params)
    @reply.user = current_user

    if @reply.save
      flash[:notice] = "Your reply has been added."
      redirect_to @comment.post
    else
      flash[:alert] = "Your reply failed to save. Please try again."
      redirect_to @comment.post
    end
  end

  def edit
  end

  def update
    @reply.assign_attributes(reply_params)

    if @reply.save
      flash[:notice] = "Your reply has been updated."
      redirect_to @comment.post
    else
      flash.now[:alert] = "There was an error updating your reply. Please try again."
      redirect_to @comment.post
    end
  end

  def destroy
    if @reply.destroy
      flash[:notice] = "Your reply was removed."
    else
      flash[:alert] = "Your reply was not removed. Please try again."
    end
    redirect_to @comment.post
  end

  def like
    @like = Like.where(likeable: @reply, user_id: current_user)

    unless @like.size >= 1
      Like.create(likeable: @reply,  user: current_user, like: params[:like])
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:body)
  end

  def set_reply
    @reply = Reply.find(params[:id])
  end

  def set_comment
    @comment = Comment.find(params[:comment_id])
  end

  def spam_detected
    redirect_to root_path
  end

  def authorize_user
    unless current_user && (current_user.member? || current_user.admin?)
      flash[:alert] = "You must be member to reply. Sign up for free now!"
      redirect_to root_path
    end
  end

end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for [@post,@comment,@reply] do |f| %>

  <%= f.invisible_captcha :subtitle %>

  <div class="form-field col-xs-12 col-md-8">
    <%= f.text_area :body, class: 'form-control' %>
  </div><br>

  <div class="form-field col-xs-12 col-md-8">
    <%= f.submit "Add Reply", class: "rfp-btn btn btn-lg btn-info" %>
  </div><br>
<% end %>

app/views/replies/_reply.html.erb
<% if @comment.replies.empty? %>
  <h3 class="comment-notes">No replies for above comment</h3>
<% else %>
    <div class="reply-section">

        <% @comment.replies.each do |reply| %>
            <div class="comment-section border-reply col-xs-12 col-md-12 col-lg-8">
                <p class="text-primary font-italic"><%= reply.user.email.split('@')[0] %>
                  <span class="text-muted">
                    <%= "- " + time_ago_in_words(reply.created_at) + " ago" %>
                  </span>
                </p>
                <p><%= reply.body %></p>
                <div class="row">
                  <% if current_user %>
                      <div class="col-md-4 like-container">
                          <%= link_to like_comment_reply_path(@comment,reply, like: true), method: 'post', remote: true do %>
                              <span class="like-text-comment">Like</span><i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                              <span id="reply_<%= reply.id %>_likes"><%= reply.likes.size %></span>
                          <% end %>
                      </div>
                  <% end %>
                    <div class="col-md-8 ud-reply">
                        <% if reply.user === current_user || (current_user && current_user.admin?) %>
                            <%= link_to "delete", comment_reply_path(@comment, reply),
                              method: :delete, class: "rfp-btn btn btn-sm btn-info", data: { confirm: "Are you sure you want to delete this comment?"} %>
                              <%= link_to "edit", edit_comment_reply_path(@comment, reply), class: "rfp-btn btn btn-sm btn-info" %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/replies/edit.html.erb
<div class="container">
  <h3 class="font-italic comment-notes top-marg"> Edit your reply to this post </h3><br>

  <%= form_for [@post,@comment,@reply] do |f| %>

    <%= f.invisible_captcha :subtitle %>

    <div class="form-field">
      <%= f.text_area :body, class: 'form-control' %>
    </div><br>

    <div class="form-field">
      <%= f.submit "Update Reply", class: "rfp-btn btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/replies/like.js.erb
$("#reply_<%= @reply.id %>_likes").html("<%= @reply.likes.size %>");

app/views/replies/new.html.erb
<h1 class="comment-notes">Reply to:</h1><br>
<div class="comment-section jumbotron col-xs-12 col-md-12 col-lg-8">
    <p class="text-primary font-italic"><%= @comment.user.email.split('@')[0] %>
      <span class="text-muted">
        <%= "- " + time_ago_in_words(@comment.created_at) + " ago" %>
      </span>
    </p>
    <p><%= @comment.body %></p>
</div>

<%= render 'form' %>