config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'posts#index'

  resources :posts do
    collection do
       get :draft
       get :subscribe
     end

     member do
       post 'like'
     end

     resources :comments, only: [:create, :edit, :update, :destroy]
   end

  devise_for :users
  resources :users, only: [:index]

  resources :comments, only: [:show] do
    member do
      post 'like'
      get 'replies'
    end

    resources :replies do
      member do
        post 'like'
      end
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, :as => :likeable
  has_many :replies, dependent: :destroy

  after_create :send_comment_notification

  default_scope { order('created_at DESC') }

  validates :body, presence: true

  def send_comment_notification
    post = self.post
    comment = self
    if Rails.env.production?
      recipients = User.where(role: "admin").pluck(:email)
      recipients.each do |recipient|
        UserMailer.comment_notification(post, comment, recipient).deliver_later
      end
    else
      UserMailer.comment_notification(post, comment, "isorme1@gmail.com").deliver_later
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  invisible_captcha only: [:create, :update], honeypot: :subtitle, on_spam: :spam_detected
  before_action :authorize_user, except: [:index, :show, :like, :replies]
  before_action :set_post, only: [:create, :edit, :update, :destroy]
  before_action :set_comment, only: [:show, :edit, :update, :like, :replies]

  def show
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Your comment has been added."
    else
      flash[:alert] = "Comment failed to save. Please try again."
      redirect_to @post
    end
  end

  def edit
  end

  def update
    @comment.assign_attributes(comment_params)

    if @comment.save
      flash[:notice] = "Your comment has been updated."
      redirect_to @post
    else
      flash.now[:alert] = "Your comment failed to update. Please try again."
      render :edit
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if @comment.destroy
      flash[:notice] = "Your comment was removed."
      redirect_to @post
    else
      flash[:alert] = "Your comment could not be removed. Please try again."
      redirect_to @post
    end
  end

  def replies
  end

  def like
    @like = Like.where(likeable: @comment, user_id: current_user)

    unless @like.size >= 1
      Like.create(likeable: @comment,  user: current_user, like: params[:like])
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def spam_detected
    redirect_to root_path
  end

  def authorize_user
    unless current_user
      flash[:alert] = "You must be atleast a member to comment. Sign up for free now!"
      redirect_to root_path
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @post.comments.each do |comment| %>
    <div class="comment-section col-xs-12 col-md-12 col-lg-8">
        <p class="text-primary font-italic"><%= comment.user.email.split('@')[0] %>
            <span class="text-muted">
              <%= "- " + time_ago_in_words(comment.created_at) + " ago" %>
            </span>
        </p>
        <p><%= comment.body %></p>

        <div class="row">
            <% if current_user %>
                <div class="col-md-3 like-container">
                    <%= link_to like_comment_path(comment, like: true), method: 'post', remote: true do %>
                        <span class="like-text-comment">Like</span><i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                        <span id="comment_<%= comment.id %>_likes"><%= comment.likes.size %></span>
                    <% end %>
                </div>
            <% end %>
            <div class="col-md-5 reply-container">
              <% if current_user %>
                 <span class="reply-to-comment"> <%= link_to "Reply", new_comment_reply_path(comment) %> </span>
                 <span> | </span>
              <% end %>
               <span class="like-text-comment"><%= link_to "View replies", replies_comment_path(comment), class: "replies#{comment.id} show-replies", remote: true %></span>
               <span class="like-text-comment"><%= "#{comment.replies.count}"%></span>
            </div>
            <div class="col-md-4">
              <% if comment.user === current_user || (current_user && current_user.admin?) %>
                <%= link_to "delete", post_comment_path(@post,comment),
                  method: :delete, class: "rfp-btn btn btn-sm btn-info", data: { confirm: "Are you sure you want to delete this comment?"} %>
                  <%= link_to "edit", edit_post_comment_path(@post,comment), class: "rfp-btn btn btn-sm btn-info" %>
              <% end %>
            </div>
        </div>
    </div>
       <div class="replies-display<%=comment.id%> reply-display"></div>
<% end %>

app/views/comments/_form.html.erb
<div class="row">
  <h3 class="font-italic comment-notes col-xs-12 col-md-8"> Leave a comment </h3>
</div>

<%= form_for [post,comment], remote: true, :html => { :id => 'comment_form' } do |f| %>
  <%= f.invisible_captcha :subtitle %>

    <div class="form-group">
      <%= f.text_area :body, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit "Add Comment", class: "rfp-btn btn btn-info" %>
    </div><br>
<% end %>

app/views/comments/create.js.erb
$('.comments-display<%=@post.id%>').html("").append("<%= escape_javascript(render @comment) %>");
$('#comment_form')[0].reset();

app/views/comments/edit.html.erb
<div class="container">
  <h3 class="font-italic comment-notes top-marg"> Edit your comment for this post </h3><br>

  <%= form_for [@post,@comment] do |f| %>
    <%= f.invisible_captcha :subtitle %>
    <div class="form-field">
      <%= f.text_area :body, class: 'form-control' %>
    </div><br>

    <div class="form-field">
      <%= f.submit "Update Comment", class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/comments/like.js.erb
$("#comment_<%= @comment.id %>_likes").html("<%= @comment.likes.size %>");

app/views/comments/replies.js.erb
if ($(".replies<%=@comment.id%>").text() === "View replies") {
  $(".replies-display<%= @comment.id %>").html("<%= j render 'replies/reply' %>");
  $(".replies<%=@comment.id%>").html("Hide replies")
} else {
  $(".replies-display<%= @comment.id %>").html("")
  $(".replies<%=@comment.id%>").html("View replies")
}