config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'posts#index'

  resources :posts do
    collection do
       get :draft
       get :subscribe
     end

     member do
       post 'like'
     end

     resources :comments, only: [:create, :edit, :update, :destroy]
   end

  devise_for :users
  resources :users, only: [:index]

  resources :comments, only: [:show] do
    member do
      post 'like'
      get 'replies'
    end

    resources :replies do
      member do
        post 'like'
      end
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, :as => :likeable

  scope :draft, -> { where(draft: true) }
  scope :published, -> { where(draft: [nil, false]).order('created_at DESC') }

  validates :title, length: { minimum: 4 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true

  after_commit :send_post_notification, on: [:create, :update], :if => :notify_of_post?

  paginates_per 5

  mount_uploader :cover, BlogImageUploader

  def send_post_notification
    recipients = User.where(subscription: true).pluck(:email)
    post = self
    recipients.each do |recipient|
      UserMailer.post_notification(recipient, post).deliver_later
    end
  end

  def notify_of_post?
    self.notify?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :replies]
  before_action :authorize_user, except: [:index, :show, :subscribe, :like]
  before_action :authorize_like, only: [:like]

  def index
    ahoy.track "Viewed Home Page"
    @posts = Post.published.page params[:page]
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      flash[:notice] = "Your blog post was successfully added."
      redirect_to @post
    else
      flash[:alert] = "There was an error creating your blog post. Please try again."
      render :new
    end
  end

  def edit
  end

  def update
    @post.assign_attributes(post_params)

    if @post.save
      flash[:notice] = "Your blog post has been successfully updated."
      redirect_to @post
    else
      flash.now[:alert] = "There was an error updating your blog post. Please try again."
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = "Your blog post was removed."
      redirect_to root_path
    else
      flash[:alert] = "Your blog post could not be removed. Please try again."
      redirect_to root_path
    end
  end

  def draft
    @drafts = Post.draft
  end

  #this needs to be moved to the users controller and refactored as well
  def subscribe
    if current_user.subscription?
      current_user.subscription = false
    else
      current_user.subscription = true
    end

    if current_user.save
      if current_user.subscription?
        flash[:notice] = "You have successfully subscribed!"
        redirect_to root_path
      else
        flash[:alert] = "You are now unsubscribed."
        redirect_to root_path
      end
    else
      flash[:warning] = "There was an error. Please try again."
      redirect_to root_path
    end
  end

  def like

    @like = Like.where(likeable: @post, user_id: current_user)

    unless @like.size >= 1
      Like.create(likeable: @post, user: current_user, like: params[:like])
    end
  end


  private

  def post_params
    params.require(:post).permit(:title, :body, :cover, :draft, :notify)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def authorize_user
    unless current_user && current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end

  def authorize_like
    unless current_user
      flash[:alert] = "You must be signed in to like a post. Don't forget to check the Remember Me box to avoid having to sign in every time!"
      redirect_to new_user_session_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@post.errors.count, "error") %></h4>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(@post.errors[:title]) do %>
    <%= f.label :title, class: "comment-notes" %>
    <%= f.text_field :title, class: "form-control" %>
  <% end %>

  <%= form_group_tag(@post.errors[:body]) do %>
    <%= f.label :body, class: "comment-notes" %>
    <%= f.cktext_area :body, class: "form-control" %>
  <% end %>

  <%= form_group_tag(@post.errors[:cover]) do %>
    <%= f.label "Cover Photo" , class: "comment-notes" %>
    <%= f.file_field :cover %>
  <% end %>

  <div class="form-field">
    <%= f.label "Save as Draft?", class: "comment-notes" %>
    <%= f.check_box :draft %>
  </div><br>

  <div class="form-field">
    <%= f.label "Send notification emails?", class: "comment-notes" %>
    <%= f.check_box :notify %>
  </div><br>

  <div class="form-field">
    <%= f.submit "Save", class: "rfp-btn btn btn-info" %>
  </div><br>
<% end %>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
    <div class="blog-container">
        <div class="row">
            <div class="post-prev-title col-md-12">
               <h2 class="title-font font-italic"><%= post.title %></h2>
               <p class="text-muted font-italic"><%= post.created_at.strftime("%Y-%m-%d") + " By Robin & Gloria" %></p>
            </div>
            <div class="col-md-7 preview-div">
                 <div class="preview-blog-text">
                     <p><%= raw post.body.truncate(250) %></p>
                     <div class="text-left">
                         <%= link_to post_path(post), :class => "rfp-btn btn btn-info btn-lg"  do %>
                             Read Full Post
                         <% end %>
                     </div><br>
                 </div>
            </div>
            <% if post.cover? %>
              <div class="col-md-5">
                <div class="image-div">
                   <%= image_tag(post.cover.url, alt: "Cover Image for #{post.title}", class: "cover-image") %>
                 </div>
              </div>
            <% end %>
        </div><br>
        <% if current_user && current_user.admin? %>
          <div class="row">
              <div class="col-md-6 text-center">
                  <%= link_to "delete post", post_path(post), method: :delete, class: "rfp-btn btn btn-sm btn-info",
                    data: { confirm: "Are you sure you want to delete this blog post?" } %>
                  <%= link_to "edit post", edit_post_path(post), class: "rfp-btn btn btn-sm btn-info" %>
              </div>
          </div><br>
        <% end %>
    </div>
<% end %>

<%= paginate @posts %>

app/views/posts/draft.html.erb
<% if @drafts.empty? %>
  <p class="top-marg comment-notes">No Drafts Here Yet</p>
<% else %>
  <h1 class="title-font text-primary text-center"> Blog Drafts </h1><br>
  <% @drafts.each do |draft| %>
    <div class="blog-container">
        <div class="row">
            <div class="post-prev-title col-md-12">
               <h2 class="title-font font-italic"><%= draft.title %></h2>
               <p class="text-muted font-italic"><%= draft.created_at.strftime("%Y-%m-%d") + " By Robin & Gloria" %></p>
            </div>
            <div class="col-md-7 preview-div">
                 <div class="preview-blog-text">
                     <p><%= raw draft.body.truncate(250) %></p>
                     <div class="text-left">
                         <%= link_to post_path(draft), :class => "rfp-btn btn btn-info btn-lg"  do %>
                             Read Full Post
                         <% end %>
                     </div><br>
                 </div>
            </div>
            <% if draft.cover? %>
              <div class="col-md-5">
                <div class="image-div">
                   <%= image_tag(draft.cover.url, alt: "Cover Image for #{draft.title}", class: "cover-image") %>
                 </div>
              </div>
            <% end %>
        </div><br>
        <% if current_user && current_user.admin? %>
          <div class="row">
              <div class="col-md-6 text-center">
                  <%= link_to "delete draft", post_path(draft), method: :delete, class: "rfp-btn btn btn-sm btn-info",
                    data: { confirm: "Are you sure you want to delete this blog draft?" } %>
                  <%= link_to "edit draft", edit_post_path(draft), class: "rfp-btn btn btn-sm btn-info" %>
              </div>
          </div><br>
        <% end %>
    </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class="container edit-post-container">
  <h1 class="font-italic title-font top-marg">Edit Post</h1><br>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="background-img"></div>
<div class="row">
    <div class="col-md-12">
        <div class="jumbotron text-center blog-banner">
          <% if current_user && current_user.admin? %>
            <p class="comment-notes"><%= link_to "Current Users", users_path, class: "current-users-txt" %></p>
          <% end %>
            <h1 class="font-italic title-font banner-title-text">Robin And Gloria's Travel Blog</h1>
            <% if current_user && current_user.subscription? %>
               <%= link_to "Unsubscribe", subscribe_posts_path, class: "rfp-btn btn btn-lg btn-info" %>
            <% elsif current_user %>
               <p class="guest-text text-info"> Click subscribe for email notifications of new posts</p>
               <%= link_to "Subscribe", subscribe_posts_path, class: "rfp-btn btn btn-lg btn-info" %>
            <% else %>
                <p class="guest-text text-info">Sign up or log in to an existing account to enjoy full access</p>
                <%= link_to "Sign up",  new_user_registration_path, class: "rfp-btn btn btn-lg btn-info" %>
            <% end %>
        </div>
    </div>
</div><br><br>

<% unless current_user %>
  <div class="speech-bubble-container">
    <div class="speech-bubble">
        <p><%= "Thanks for stopping by, but you aren't signed in! Remember to sign-in and check the 'Remember Me' box so you
        are signed in automatically next time!" %></p>
        <%= link_to "Sign in here", new_user_session_path %>
    </div>
    <div class="greeting-bot">
      <%= image_tag('greeting-bot.png', alt: "Greeting Bot", class: "greeting-bot-img") %>
    </div>
  </div>
<% end %>


<% if current_user && current_user.admin? %>
    <div class="row">
        <div class="col-md-12 text-center">
            <%= link_to "Create New Post", new_post_path, class: "rfp-btn btn btn-lg btn-info" %>
        </div>
    </div><br>
<% end %>

<%= render 'posts' %>

app/views/posts/like.js.erb
$("#post_<%= @post.id %>_likes").html("<%= @post.likes.size %>");

app/views/posts/new.html.erb
<h1 class="title-font font-italic top-marg">New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<main class="container">
  <div class="row post-show-title text-center">
    <div class="col-md-12">
      <h1 class="font-italic title-font text-center"><%= @post.title %></h1>
    </div>
  </div><br>
  <div class="row">
    <div class="text-center post-show-title-image-banner">
       <%= image_tag("#{@post.cover}", alt: "Cover Image for #{@post.title}", class: "cover-image-show") %>
     </div>
  </div><br>
  <div class="row">
    <div>
      <div class="post-show-blog">
        <p><%= raw @post.body %></p>
      </div><br>

        <div class="like-post-container">
            <%= link_to like_post_path(@post, like: true), method: 'post', remote: true do %>
                <span class="like-text-post">Like Post</span><i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
                <span id="post_<%= @post.id %>_likes"><%= @post.likes.size %></span>
            <% end %>
        </div><br>

      <% if current_user %>
        <%= render 'comments/form', comment: Comment.new, post: @post %>
      <% else %>
        <h3 class="font-italic comment-notes">You must be signed in to comment</h3><br>
      <% end %>
      <h3 class="comment-header font-italic">Comments</h3><br>
      <div class="comments-display<%=@post.id%>">
        <%= render 'comments/comment' %>
      </div>
    </div>
  </div><br>
</main>

app/views/posts/show.js.erb
if ($(".comments<%=@post.id%>").text() === "View comments") {
  $(".comments-display<%= @post.id %>").html("<%= j render "comments/comment" %>")
  $(".comments<%=@post.id%>").html("Hide comments")
} else {
  $(".comments-display<%= @post.id %>").html("")
  $(".comments<%=@post.id%>").html("View comments")
}