config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root 'posts#index'

  resources :posts do
    collection do
       get :draft
       get :subscribe
     end

     member do
       post 'like'
     end

     resources :comments, only: [:create, :edit, :update, :destroy]
   end

  devise_for :users
  resources :users, only: [:index]

  resources :comments, only: [:show] do
    member do
      post 'like'
      get 'replies'
    end

    resources :replies do
      member do
        post 'like'
      end
    end
  end

end

app/views/layouts/_messages.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
    </div>
<% elsif flash[:alert] %>
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Robin And Gloria's Blog</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
         <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body class="<%= controller_name %> <%= action_name %>">
        <header>
            <nav class="navbar navbar-expand-sm navbar-light navvy">
                <%= link_to "Robin & Gloria's Blog", root_path, class: "navbar-brand navbar-font font-italic" %>
                <button class="navbar-toggler custom-toggler" data-toggle="collapse" data-target="#navbarMenu">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarMenu">
                    <ul class="navbar-nav ml-auto font-italic">
                        <% if current_user && current_user.admin? %>
                            <li class="nav-item cust-nav-item"><%= link_to "Drafts", draft_posts_path, class: "nav-link nav-link-font" %></li>
                        <% end %>
                        <% if current_user %>
                            <li class="nav-item cust-nav-item"><%= link_to "Home", root_path, class: "nav-link nav-link-font" %></li>
                            <li class="nav-item cust-nav-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link nav-link-font" %></li>
                            <li class="nav-item cust-nav-item"><%= link_to "#{current_user.email.truncate(18)}", edit_user_registration_path, class: "nav-link nav-link-font" %></li>
                        <% else %>
                            <li class="nav-item cust-nav-item"><%= link_to "Home", root_path, class: "nav-link nav-link-font" %></li>
                            <li class="nav-item cust-nav-item"><%= link_to "Sign up", new_user_registration_path, class: "nav-link nav-link-font" %></li>
                            <li class="nav-item cust-nav-item"><%= link_to "Login",  new_user_session_path, class: "nav-link nav-link-font" %></li>
                        <% end %>
                    </ul>
                </div>
            </nav>
        </header>

        <div class="flash">
          <%= render 'layouts/messages' %>
        </div>

        <div class="container-fluid yield-container">
          <%= yield %>
        </div>

    </body>
</html>